name: committer

on:
  push:
    branches:
      - master
 schedule:
   - cron: "1,3,4,7 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto Green
        run: |
          git config --local user.email "softwarelab@yeah.net"
          git config --local user.name "Ezharjan"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "auto commit"
          git push
